README.md rework
nanobox-quickstarts/nanobox-rails pull request #7
Opened 2017-10-18 10:59 UTC by AidanDavidWard

2017-10-18 10:59 UTC, AidanDavidWard commented
@sdomino Better?

2017-10-19 16:19 UTC, sdomino requested changes
Looks good. I made a few minor suggestions. Once those are updated I'll merge. Thanks!

2017-10-19 16:19 UTC, sdomino commented on README.md
> +1. Clone the nanobox repo
Clone the nanobox repo -> Clone this repo

2017-10-19 16:19 UTC, sdomino commented on README.md
> +2. Don't forget to cd into the new directory
Don't forget to cd into the new directory -> Change into the directory

2017-10-19 16:19 UTC, sdomino commented on README.md
> +4. Run rake to create a database
Run rake to create a database -> Create the database

2017-10-24 08:15 UTC, AidanDavidWard commented
@sdomino There we go. Let me know if theres anything else. I'll try and respond faster this time 😄

2017-10-24 14:06 UTC, merged